blank_issues_enabled: true

contact_links:
  - name: Discussions on GitHub
    url: https://github.com/honey-team/ufpy/discussions
    about: Ask your question in GitHub discussions
  - name: Discord server
    url: https://discord.honey-team.ru
    about: Ask your question on our official Discord Server (verified custom domain)
  - name: Telegram channel
    url: https://tg.honey-team.ru
    about: Ask your question on our official Telegram channel (in HoneyTeam Chat) (verified custom domain)