name: ci
on:
  push:
    branches:
      - 0.1 docs
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Init caching
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Install requirements
        run: pip install -r docs/requirements.txt
      - name: Deploy mkdocs documentation
        run: mkdocs gh-deploy --force